INSERT INTO quotes (quote, character, source, slug) VALUES
  ('  I am no man!      ', 'EOWYN', 'The Return of the King ', 'eowyn-no-man', FALSE),
  ('This task was appointed to you, Frodo of the Shire. If you do not find a     way, no one will.  ', 'GALADRIEL', 'The Return of the King ', 'frodo-appointed-task', FALSE),
  ('This task was appointed to you, Frodo of the Shire. If you do not find a     way, no one will.  ', 'GALADRIEL', 'The Return of the King ', 'find-your-way', FALSE),
  ('This task was appointed to you, Frodo of the Shire. If you do not find a     way, no one will.  ', 'GALADRIEL', 'The Return of the King ', 'galadriel-burden-shire', FALSE),
  ('I cannot jump the distance! You''ll have to toss me!       ', 'GIMLI', 'The Two Towers ', 'gimli-toss-me', FALSE),
  ('I cannot jump the distance! You''ll have to toss me!       ', 'GIMLI', 'The Two Towers ', 'dwarf-cannot-jump', FALSE),
  ('I know. It''s all wrong.      ,By rights, we shouldn''t even be here.      But we are. It''s like in the great stories, Mr. Frodo. The ones that really mattered.      ,Full of darkness and danger they were.      And sometimes you didn''t want to know the end.....because how could the end be happy?       How could the world go back      to the way it was...... when so much bad had happened?           ', 'SAM', 'The Two Towers ', 'sam-great-stories', FALSE),
  ('I know. It''s all wrong.      ,By rights, we shouldn''t even be here.      But we are. It''s like in the great stories, Mr. Frodo. The ones that really mattered.      ,Full of darkness and danger they were.      And sometimes you didn''t want to know the end.....because how could the end be happy?       How could the world go back      to the way it was...... when so much bad had happened?           ', 'SAM', 'The Two Towers ', 'darkness-and-danger', FALSE),
  ('I know. It''s all wrong.      ,By rights, we shouldn''t even be here.      But we are. It''s like in the great stories, Mr. Frodo. The ones that really mattered.      ,Full of darkness and danger they were.      And sometimes you didn''t want to know the end.....because how could the end be happy?       How could the world go back      to the way it was...... when so much bad had happened?           ', 'SAM', 'The Two Towers ', 'world-goes-wrong', FALSE),
  ('But in the end, it''s only a passing thing...... this shadow. Even darkness must pass.      A new day will come. And when the sun shines, it will shine out the clearer.      Those were the stories      that stayed with you......that meant something. Even if you were too small      to understand why. But I think, Mr. Frodo, I do understand. I know now.           ', 'SAM VOICEOVER', 'The Two Towers ', 'sam-understands', FALSE),
  ('But in the end, it''s only a passing thing...... this shadow. Even darkness must pass.      A new day will come. And when the sun shines, it will shine out the clearer.      Those were the stories      that stayed with you......that meant something. Even if you were too small      to understand why. But I think, Mr. Frodo, I do understand. I know now.           ', 'SAM VOICEOVER', 'The Two Towers ', 'shadow-passes-frodo', FALSE),
  ('But in the end, it''s only a passing thing...... this shadow. Even darkness must pass.      A new day will come. And when the sun shines, it will shine out the clearer.      Those were the stories      that stayed with you......that meant something. Even if you were too small      to understand why. But I think, Mr. Frodo, I do understand. I know now.           ', 'SAM VOICEOVER', 'The Two Towers ', 'new-day-shines', FALSE),
  ('That there''s some good in this world, Mr. Frodo. And it''s worth fighting for.           ', 'SAM', 'The Two Towers ', 'sam-fights-good', FALSE),
  ('That there''s some good in this world, Mr. Frodo. And it''s worth fighting for.           ', 'SAM', 'The Two Towers ', 'frodo-world-worth', FALSE),
  ('That doesn''t make sense to me.      But then......you are very small. ,Perhaps you''re right. South it is, then.      Hold on, little Shirelings. ,I always like going south. Somehow it feels like going downhill.,     ', 'TREEBEARD', 'The Two Towers ', 'treebeard-small', FALSE),
  ('That doesn''t make sense to me.      But then......you are very small. ,Perhaps you''re right. South it is, then.      Hold on, little Shirelings. ,I always like going south. Somehow it feels like going downhill.,     ', 'TREEBEARD', 'The Two Towers ', 'southbound-feeling', FALSE),
  ('That doesn''t make sense to me.      But then......you are very small. ,Perhaps you''re right. South it is, then.      Hold on, little Shirelings. ,I always like going south. Somehow it feels like going downhill.,     ', 'TREEBEARD', 'The Two Towers ', 'shirelings-hold', FALSE),
  ('What''s taters, precious?What''s taters? Eh? ', 'GOLLUM', 'The Two Towers ', 'gollum-precious-taters', FALSE),
  ('    By all that you hold dear on this good earth, I bid you stand! Men of the     West! ', 'ARAGORN', 'The Return of the King ', 'aragorn-stand-firm', FALSE),
  ('    By all that you hold dear on this good earth, I bid you stand! Men of the     West! ', 'ARAGORN', 'The Return of the King ', 'men-of-west', FALSE),
  ('    Then let us be rid of it once and for all! Come on Mr Frodo, I can''t carry     it for you, but I can carry you! Come on!  ', 'SAM', 'The Return of the King ', 'sam-carries-frodo', FALSE),
  ('    Then let us be rid of it once and for all! Come on Mr Frodo, I can''t carry     it for you, but I can carry you! Come on!  ', 'SAM', 'The Return of the King ', 'burden-be-rid', FALSE),
  ('    Then let us be rid of it once and for all! Come on Mr Frodo, I can''t carry     it for you, but I can carry you! Come on!  ', 'SAM', 'The Return of the King ', 'faithful-companion-sam', FALSE),
  ('I''m wasted on cross-country.We Dwarves are natural sprinters.Very dangerous over short distances.', 'GIMLI', 'The Two Towers ', 'gimli-sprinter-short', FALSE),
  ('I''m wasted on cross-country.We Dwarves are natural sprinters.Very dangerous over short distances.', 'GIMLI', 'The Two Towers ', 'dwarves-dangerous-distance', FALSE),
  ('You cannot pass! ', 'GANDALF VOICE OVER', 'The Two Towers ', 'gandalf-shall-not-pass', FALSE),
  ('The Uruks turn northeast.They are taking the Hobbits to lsengard.', 'LEGOLAS', 'The Two Towers ', 'legolas-uruk-northeast', FALSE),
  ('The Uruks turn northeast.They are taking the Hobbits to lsengard.', 'LEGOLAS', 'The Two Towers ', 'hobbit-isengard-taken', FALSE),
  ('The beacons of Minas Tirith!  The beacons are lit!   ', 'ARAGORN', 'The Return of the King ', 'aragorn-beacons-lit', FALSE),
  ('Gondor calls for aid. ', 'ARAGORN', 'The Return of the King ', 'gondor-calls-aid', FALSE),
  ('Looks like meat''s back on the menuboys. ', 'UGLUK', 'The Two Towers ', 'ugluk-meat-menu', FALSE),
  ('One does not simply walk into Mordor.  Its black gates     are guarded by more than just orcs. There is evil there that does not sleep     and the great eye is ever watchful.  Tis a barren wasteland, riddled     with fire and ash and dust.  The very air you breathe is a poisonous     fume.  Not with ten thousand men could you do this.    ,It is folly ', 'BOROMIR', 'The Fellowship of the Ring ', 'boromir-folly', FALSE),
  ('One does not simply walk into Mordor.  Its black gates     are guarded by more than just orcs. There is evil there that does not sleep     and the great eye is ever watchful.  Tis a barren wasteland, riddled     with fire and ash and dust.  The very air you breathe is a poisonous     fume.  Not with ten thousand men could you do this.    ,It is folly ', 'BOROMIR', 'The Fellowship of the Ring ', 'mordor-wasteland', FALSE),
  ('One does not simply walk into Mordor.  Its black gates     are guarded by more than just orcs. There is evil there that does not sleep     and the great eye is ever watchful.  Tis a barren wasteland, riddled     with fire and ash and dust.  The very air you breathe is a poisonous     fume.  Not with ten thousand men could you do this.    ,It is folly ', 'BOROMIR', 'The Fellowship of the Ring ', 'evil-watchful', FALSE),
  ('A wizard is never late! Frodo Baggins.    , Nor is he early, he arrives precisely when he means     to.       ', 'GANDALF', 'The Fellowship of the Ring ', 'gandalf-arrives-precisely', FALSE),
  ('A wizard is never late! Frodo Baggins.    , Nor is he early, he arrives precisely when he means     to.       ', 'GANDALF', 'The Fellowship of the Ring ', 'wizard-never-late', FALSE),
  ('I wish the Ring had never come to me.  I wish none of     this had happened. ', 'FRODO', 'The Fellowship of the Ring ', 'frodo-wishes-differently', FALSE),
  ('I wish the Ring had never come to me.  I wish none of     this had happened. ', 'FRODO', 'The Fellowship of the Ring ', 'ring-never-came', FALSE),
  ('So do all who live to see such times, but that is not for     them to decide.  All we have to decide is what to do with the time that     is given to us.  There are other forces at work in this world, Frodo,     besides the will of evil.  Bilbo was meant to find the Ring, in which     case you also were meant to have it and that is an encouraging thought.        Oh! Its that way ', 'GANDALF', 'The Fellowship of the Ring ', 'gandalf-decide-time', FALSE),
  ('So do all who live to see such times, but that is not for     them to decide.  All we have to decide is what to do with the time that     is given to us.  There are other forces at work in this world, Frodo,     besides the will of evil.  Bilbo was meant to find the Ring, in which     case you also were meant to have it and that is an encouraging thought.        Oh! Its that way ', 'GANDALF', 'The Fellowship of the Ring ', 'frodo-meant-ring', FALSE),
  ('So do all who live to see such times, but that is not for     them to decide.  All we have to decide is what to do with the time that     is given to us.  There are other forces at work in this world, Frodo,     besides the will of evil.  Bilbo was meant to find the Ring, in which     case you also were meant to have it and that is an encouraging thought.        Oh! Its that way ', 'GANDALF', 'The Fellowship of the Ring ', 'bilbo-encouraging-thought', FALSE),
  ('      They have taken the Bridge and the second hall.  We have barred the     gates, but cannot hold them for long.  The ground shakes.  Drums    ,     Drums in the deep. We cannot get out. , A shadow moves in the dark.    , We cannot get out. They are     coming. ', 'GANDALF', 'The Fellowship of the Ring ', 'drums-in-deep', FALSE),
  ('      They have taken the Bridge and the second hall.  We have barred the     gates, but cannot hold them for long.  The ground shakes.  Drums    ,     Drums in the deep. We cannot get out. , A shadow moves in the dark.    , We cannot get out. They are     coming. ', 'GANDALF', 'The Fellowship of the Ring ', 'gandalf-barred-gates', FALSE),
  ('      They have taken the Bridge and the second hall.  We have barred the     gates, but cannot hold them for long.  The ground shakes.  Drums    ,     Drums in the deep. We cannot get out. , A shadow moves in the dark.    , We cannot get out. They are     coming. ', 'GANDALF', 'The Fellowship of the Ring ', 'shadow-moves-dark', FALSE),
  ('Fool of a Took!  ', 'GANDALF', 'The Return of the King ', 'gandalf-fool-took', FALSE),
  ('They have a cave troll! ', 'BOROMIR', 'The Fellowship of the Ring ', 'boromir-cave-troll', FALSE),
  ('What about elvenses ? Luncheon, Afternoon Tea, Dinner ?     Supper!  He knows about them, doesnt he ? ', 'PIPPIN', 'The Fellowship of the Ring ', 'pippin-second-breakfast', FALSE),
  ('What about elvenses ? Luncheon, Afternoon Tea, Dinner ?     Supper!  He knows about them, doesnt he ? ', 'PIPPIN', 'The Fellowship of the Ring ', 'elvenses-elevenses-meals', FALSE),
  ('Run, Shadowfax show us the meaning of haste. ', 'GANDALF', 'The Return of the King ', 'shadowfax-haste', FALSE),
  ('    Frodo, any chance of seeing that old Ring of mine again? The one I gave you? ', 'BILBO', 'The Return of the King ', 'bilbo-remembers-ring', FALSE),
  ('    We set out to save the Shire Sam and it has been saved, but not for me.  ', 'FRODO', 'The Return of the King ', 'frodo-sacrifice', FALSE),
  ('The Ring will not save Gondor.      , It has only the power to destroy.      Please......Iet me go.        ', 'FRODO', 'The Two Towers ', 'ring-destroys-all', FALSE),
  ('When last I looked......Theoden, not Aragorn, was King of Rohan. ', 'THEODEN', 'The Two Towers ', 'theoden-king-rohan', FALSE),
  ('Master says to show himthe way into Mordor.So good Smeagol doesmaster says so. ', 'GOLLUM', 'The Two Towers ', 'smeagol-shows-way', FALSE),
  ('    I can see the Shire. The Brandywine River. Bag End. Gandalf''s fireworks. The     lights on the party tree. ', 'FRODO', 'The Return of the King ', 'frodo-home-memories', FALSE),
  ('I think we might have made a mistakeleaving the Shire, Pippin. ', 'MERRY', 'The Two Towers ', 'merry-second-thoughts', FALSE),
  ('  It''s too late.  It''s over.  They''ve taken it Sam,  they took the Ring!      ', 'FRODO', 'The Return of the King ', 'ring-taken', FALSE),
  ('Mr. Frodo?It''s the Ring, isn''t it? ', 'SAM', 'The Two Towers ', 'sam-questions-ring', FALSE),
  ('Look Frodo.  It''s Mr Bilbo''s trolls ', 'SAM', 'The Fellowship of the Ring ', 'bilbo-trolls', FALSE),
  ('No Gimli, I would not take the road through Moria unless I     had no other choice. ', 'GANDALF', 'The Fellowship of the Ring ', 'gandalf-no-moria', FALSE),
  ('The Gap of Rohan takes us too close to Isengard! ', 'ARAGORN', 'The Fellowship of the Ring ', 'aragorn-gap-warning', FALSE),
  (' Have you     heard nothing Lord Elrond has said? The Ring must be destroyed ', 'LEGOLAS', 'The Fellowship of the Ring ', 'ring-must-burn', FALSE),
  ('We have time. Every day Frodo moves closer to Mordor. ', 'ARAGORN', 'The Return of the King ', 'frodo-moves-on', FALSE),
  ('I have to leave the Shire. ,Sam and I must get to Bree ', 'FRODO', 'The Fellowship of the Ring ', 'frodo-leaves-shire', FALSE),
  ('The wealth of Moria is not in gold, or jewels, but Mithril ', 'GANDALF', 'The Fellowship of the Ring ', 'gandalf-mithril-treasure', FALSE),
  ('Bilbo had a shirt of mithril rings that Thorin gave him ', 'GANDALF', 'The Fellowship of the Ring ', 'bilbo-mithril-gift', FALSE),
  ('I know Sam, I know. Trust me. Come Smeagol. ', 'FRODO', 'The Return of the King ', 'frodo-trusts-sam', FALSE),
  ('Haven''t you had any sleep Mr Frodo?  ', 'SAM', 'The Return of the King ', 'frodo-needs-rest', FALSE),
  ('Not before Mr Frodo''s had something to eat.  ', 'SAM', 'The Return of the King ', 'frodo-must-eat', FALSE),
  ('Oh no, I''m not hungry, leastways not for lembas bread.  ', 'SAM', 'The Return of the King ', 'sam-tired-bread', FALSE),
  ('Come Hobbitses, very close now. Very close to Mordor. No safe places here. Hurry.  ', 'GOLLUM', 'The Return of the King ', 'gollum-hurry-close', FALSE),
  ('It''s good. Definitely from the Shire. ,Longbottom leaf eh?  ', 'MERRY', 'The Return of the King ', 'merry-longbottom-leaf', FALSE),
  ('You young rascals. A merry hunt you''ve led us on and now we find you     feasting and '' and smoking!  ', 'GIMLI', 'The Return of the King ', 'gimli-merry-hunt', FALSE),
  ('    It''s been four years to the day since Weathertop Sam. It''s never really     healed.  ', 'FRODO', 'The Return of the King ', 'weathertop-wound', FALSE),
  ('We''re under orders from Treebeard who''s taken over management of Isengard.        ', 'MERRY', 'The Return of the King ', 'merry-takes-command', FALSE),
  ('    Gandalf! ,     Gandalf! Denethor has lost his mind. He''s burning Faramir alive!  ', 'PIPPIN', 'The Return of the King ', 'denethor-burns-faramir', FALSE),
  ('  Mr Frodo, look. ,  There is light and beauty up there that no shadow can touch.      ', 'SAM', 'The Return of the King ', 'light-touches-shadow', FALSE),
  ('  I don''t think there will be a return journey Mr Frodo.      ', 'SAM', 'The Return of the King ', 'sam-no-return', FALSE),
  ('Legolas, fire a warning shot past the boson''s ear.  ', 'ARAGORN', 'The Return of the King ', 'legolas-warning-shot', FALSE),
  ('It is a three-day gallop to Minas Tirith and none of my riders can bear     you as a burdon.  ', 'THEODEN', 'The Return of the King ', 'theoden-burden', FALSE),
  ('Ach! You waste your time Aragorn. They had no honour in life and they     have none now in death.  ', 'GIMLI', 'The Return of the King ', 'gimli-dishonored-dead', FALSE),
  ('Every hour lost hastens Gondor''s defeat.  ,  We have until dawn then we must ride.   ', 'ARAGORN', 'The Return of the King ', 'aragorn-rides-dawn', FALSE),
  ('You might as well accept it.  We''re going with you laddie.  Aragorn     smiles. ', 'GIMLI', 'The Return of the King ', 'gimli-accepts-quest', FALSE),
  ('Smeagol?  No, no, not poor Smeagol.  Smeagol hates nasty elf bread.      ', 'GOLLUM', 'The Return of the King ', 'smeagol-hates-bread', FALSE),
  ('No Sam!  It''s you!  ,      I''m sorry Sam.   ', 'FRODO', 'The Return of the King ', 'frodo-apologies', FALSE),
  ('(looking back out to Mordor) All our hopes now lie with two little Hobbits...           ', 'GANDALF', 'The Two Towers ', 'gandalf-little-hope', FALSE),
  ('What does that mean? What''s wrong?  He looks at Gandalf. ', 'PIPPIN', 'The Return of the King ', 'pippin-questions-gandalf', FALSE),
  ('Well, you''ve left out one of the chief characters:      "Samwise the Brave."      I want to hear more about Sam.           ', 'FRODO', 'The Two Towers ', 'samwise-the-brave', FALSE),
  ('Frodo wouldn''t have got far      without Sam.           ', 'FRODO', 'The Two Towers ', 'frodo-needs-sam', FALSE),
  ('Now, Mr. Frodo, you shouldn''t make fun. I was being serious.            ', 'SAM', 'The Two Towers ', 'sam-serious-business', FALSE),
  ('Mr Frodo!  , Get back     you!  Don''t touch him.   ', 'SAM', 'The Return of the King ', 'sam-protective-stand', FALSE),
  ('Gollum says there''s a path......near Minas Morgul that climbs up into the mountains.,     ', 'FRODO', 'The Two Towers ', 'gollum-mountain-path', FALSE),
  ('lt is the only way. Master says we must go to Mordor, so we must try.           ', 'GOLLUM', 'The Two Towers ', 'gollum-only-way', FALSE),
  ('Hold on, Mr. Frodo. You''ll be all right.           ', 'SAM', 'The Two Towers ', 'sam-holds-on', FALSE),
  ('Smeagol. , Master is here.     Come, Smeagol. Trust master. Come. ', 'FRODO', 'The Two Towers ', 'smeagol-trust-master', FALSE),
  ('Don''t hurt him! ,Smeagol, don''t struggle. Smeagol, listen     to me. ', 'FRODO', 'The Two Towers ', 'smeagol-listen-please', FALSE),
  ('We are Hobbits of the Shire. Frodo Baggins is my name, and this is     Samwise Gamgee. ', 'FRODO', 'The Two Towers ', 'frodo-samwise-shire', FALSE),
  (' You''re a daughter of kings......a shieldmaiden of Rohan.I do not think that would be your fate.  ', 'ARAGORN', 'The Two Towers ', 'daughter-of-kings', FALSE),
  ('We''ve got to get moving. Come on, Sam.  ', 'FRODO', 'The Two Towers ', 'sam-lets-move', FALSE),
  ('What do you know about it?Nothing! ,I''m sorry, Sam. I don''t knowwhy I said that. ', 'FRODO', 'The Two Towers ', 'frodo-forgives-sam', FALSE),
  ('    It''s gone Mr Frodo. The light''s passed on, away towards the North.     Something''s drawn its gaze. ', 'SAM', 'The Return of the King ', 'light-drawn-north', FALSE),
  ('    Look Mr Frodo, a doorway! We''re almost there!  ', 'SAM', 'The Return of the King ', 'sam-spots-doorway', FALSE),
  ('Do not regret your decision to leave him.Frodo must finish this task alone. ', 'GANDALF', 'The Two Towers ', 'frodo-alone', FALSE),
  ('King Theoden has a good memory.He was only a small child at the time. ', 'ARAGORN', 'The Two Towers ', 'theoden-memory', FALSE),
  ('I was raised in Rivendell......for a time.Turn this fellow free. He''s     seen enough of war. ', 'ARAGORN', 'The Two Towers ', 'aragorn-raises-free', FALSE),
  ('  I know your face, Eowyn. ,  My eyes darken.     ', 'THEODEN', 'The Return of the King ', 'eowyn-darkening-eyes', FALSE),
  ('  You already did.  Eowyn, my body is broken.  You have to let me go.      ', 'THEODEN', 'The Return of the King ', 'theoden-farewell', FALSE),
  ('I know, Mr. Frodo.I doubt even these Elvish cloakswill hide us in there. ', 'SAM', 'The Two Towers ', 'sam-doubts-cloaks', FALSE),
  ('Are you saying there''s another wayinto Mordor? ', 'FRODO', 'The Two Towers ', 'frodo-secret-way', FALSE),
  ('Don''t talk to it, Merry.Don''t encourage it! ', 'PIPPIN', 'The Two Towers ', 'pippin-warns-merry', FALSE),
  ('    You are soldiers of Gondor. No matter what comes through that gate you will stand your ground. ', 'GANDALF', 'The Return of the King ', 'gandalf-stand-ground', FALSE),
  ('Pippin, everyone knows I''m the tall one.You''re the short one. ', 'MERRY', 'The Two Towers ', 'merry-tall-pippin', FALSE),
  ('No!You don''t understand. We''re Hobbits!Halflings!Shire-folk! ', 'MERRY', 'The Two Towers ', 'merry-shire-folk', FALSE),
  ('No! Don''t look down, Sam!Just keep going! ', 'FRODO', 'The Two Towers ', 'sam-keep-going', FALSE),
  ('Merry!No, Treebeard said that youshouldn''t have any. ', 'PIPPIN', 'The Two Towers ', 'pippin-merry-rules', FALSE),
  ('  We did it Mr Frodo.  We made it to Mordor.      ', 'SAM', 'The Return of the King ', 'sam-made-it', FALSE),
  ('  Frodo has passed beyond my sight. ,  The darkness is deepening.      ', 'GANDALF', 'The Return of the King ', 'frodo-passes-beyond', FALSE),
  ('  Because 10,000 Orcs now stand between Frodo and Mount Doom.     ', 'GANDALF', 'The Return of the King ', 'frodo-doom', FALSE),
  (' I think these lands were once part of the Kingdom of Gondor. ', 'FRODO', 'The Return of the King ', 'frodo-gondor-lands', FALSE),
  ('Mr Frodo, look!  The King has got a crown again.   ', 'SAM', 'The Return of the King ', 'king-has-crown', FALSE),
  ('It''s very special, that.It''s the best salt in all the Shire. ', 'SAM', 'The Two Towers ', 'sam-special-salt', FALSE),
  ('He didn''t mean for a lot of thingsto happen, Sam......but they did. ', 'FRODO', 'The Two Towers ', 'frodo-things-happen', FALSE),
  ('Let me see.Oh, yes. Lovely.Lembas bread. And look!More lembas bread. ', 'SAM', 'The Two Towers ', 'sam-lovely-bread', FALSE),
  (' My my     old ring.  Well I should... very much like to hold it again, one last     time.  ', 'BILBO', 'The Fellowship of the Ring ', 'bilbo-last-hold', FALSE),
  ('Riders of Rohan......what news from the Mark? ', 'ARAGORN', 'The Two Towers ', 'aragorn-seeks-news', FALSE),
  ('Excuse me!  , I have     a sword.  Please accept it!  , I offer you my service Theoden King. ', 'MERRY', 'The Return of the King ', 'merry-offers-service', FALSE),
  ('And gladly, I accept it.  ,      You shall be Meriadoc, esquire of Rohan.  ', 'THEODEN', 'The Return of the King ', 'meriadoc-esquire', FALSE),
  ('Gandalf told me you wereone of the river-folk. ', 'FRODO', 'The Two Towers ', 'gandalf-river-folk', FALSE),
  ('Frodo, come and help an old man ,How''s your shoulder? ', 'GANDALF', 'The Fellowship of the Ring ', 'frodo-help-gandalf', FALSE),
  ('This is Sting.You''ve seen it before......haven''t you, Gollum?Release him or I''ll cut your throat. ', 'FRODO', 'The Two Towers ', 'sting-threat', FALSE),
  ('Mr Frodo ? , Frodo! Frodo!     , I thought I''d lost you ', 'SAM', 'The Fellowship of the Ring ', 'sam-finds-frodo', FALSE),
  ('For the Shire.  Hold him, hold him down Merry!     ', 'PIPPIN', 'The Fellowship of the Ring ', 'shire-hold-fast', FALSE),
  ('The courtesy of your hall is somewhat lessened of late......Theoden     King. ', 'GANDALF', 'The Two Towers ', 'gandalf-courtesy-fades', FALSE),
  ('Mr. Frodo! It''s all right.I''m here. ', 'SAM', 'The Two Towers ', 'sam-is-here', FALSE),
  ('Come away, come away.  Look we have found it.  The way into Mordor. ', 'GOLLUM', 'The Return of the King ', 'gollum-found-way', FALSE),
  ('It reads "The Doors of Durin, Lord of Moria, Speak Friend     and Enter" ', 'GANDALF', 'The Fellowship of the Ring ', 'speak-friend-enter', FALSE),
  ('The Ring is treacherous.It will hold you to your word. ', 'FRODO', 'The Two Towers ', 'ring-treacherous-hold', FALSE),
  ('Sam! We''re still in The Shire.  What could possibly     happen! ', 'FRODO', 'The Fellowship of the Ring ', 'sam-nothing-happens', FALSE),
  ('You cannot wield it.  None of us can    , The One Ring     answers to Sauron alone. It has no other master ', 'ARAGORN', 'The Fellowship of the Ring ', 'aragorn-cannot-wield', FALSE),
  ('Theoden......son of Thengel......too long have you sat in     the Shadows. ', 'GANDALF', 'The Two Towers ', 'theoden-shadows', FALSE),
  (' Go     on Sam, ask Rosie for a dance. ', 'FRODO', 'The Fellowship of the Ring ', 'sam-dance-rosie', FALSE),
  ('It was not Theoden of Rohan who led our people to victory. ', 'THEODEN', 'The Return of the King ', 'theoden-humility', FALSE),
  ('Go on, go on ,Don''t worry Sam.  He knows the way home. ,) ', 'ARAGORN', 'The Fellowship of the Ring ', 'aragorn-knows-way', FALSE),
  ('Yes Pippin, my point is, he''s clearly over reacting! Run! ', 'MERRY', 'The Fellowship of the Ring ', 'merry-overreacting', FALSE),
  ('He''s trying to bring down the mountain! Gandalf! We must     turn back! ', 'ARAGORN', 'The Fellowship of the Ring ', 'gandalf-mountain-down', FALSE),
  ('We must get off the mountain! Make for the Gap of Rohan and     take the west road to my city! ', 'BOROMIR', 'The Fellowship of the Ring ', 'boromir-westroad', FALSE),
  ('If we cannot pass over the mountain, let us go under it! Let     us go through the Mines of Moria ', 'GIMLI', 'The Fellowship of the Ring ', 'gimli-underground', FALSE),
  (' I will be     dead before I see the Ring in the hands of an elf ', 'GIMLI', 'The Fellowship of the Ring ', 'gimli-elf-refusal', FALSE),
  ('We hear of trouble in Rohan.It goes ill with the king. ', 'ARAGORN', 'The Two Towers ', 'aragorn-rohan-trouble', FALSE),
  ('      Hold out your hand Frodo. Its quite cool.  ,  What can you see ?    , Can you see anything ? ', 'GANDALF', 'The Fellowship of the Ring ', 'frodo-cool-hand', FALSE),
  ('No. Well yes, b b b but thats not the point. The point is,     Frodo, , You''ll be     alright.  ', 'BILBO', 'The Fellowship of the Ring ', 'bilbo-reassures-frodo', FALSE),
  ('Hail Denethor son of Ecthelion, Lord and Steward of Gondor. ', 'GANDALF', 'The Return of the King ', 'gandalf-hails-denethor', FALSE),
  ('Frodo, the door! ,     sticklebacks, where is that boy! FRODO!  ', 'BILBO', 'The Fellowship of the Ring ', 'frodo-where-are-you', FALSE),
  ('What''s it saying my precious, my love? Is Smeagol losing his nerve? ', 'GOLLUM', 'The Return of the King ', 'smeagol-losing-nerve', FALSE),
  ('See? I fooled you too.Don''t worry about me, Pippin. ', 'MERRY', 'The Two Towers ', 'merry-fooled-pippin', FALSE),
  ('This new Gandalf''s more grumpythan the old one. ', 'GIMLI', 'The Two Towers ', 'gimli-grumpy-gandalf', FALSE),
  ('Boromir died to save us my kinsman and me. He fell defending us from     many foes. ', 'PIPPIN', 'The Return of the King ', 'boromir-sacrifice', FALSE),
  ('The mightiest man may be slain by one arrow and Boromir was pierced by     many. ', 'PIPPIN', 'The Return of the King ', 'boromir-fallen', FALSE),
  ('You didn''t think Id miss your Uncle Bilbo''s birthday?     ', 'GANDALF', 'The Fellowship of the Ring ', 'gandalf-never-misses', FALSE),
  ('You know Bilbo he''s got the whole place in an uproar. ', 'FRODO', 'The Fellowship of the Ring ', 'bilbo-uproar', FALSE),
  ('Half the Shire''s been invited.     And the rest of them are turning up anyway.  ', 'FRODO', 'The Fellowship of the Ring ', 'frodo-unexpected-guests', FALSE),
  ('Yes, we meant for us! Gollum, gollum. The precious will be ours once the Hobbitses are dead! ', 'SMEAGOL', 'The Return of the King ', 'smeagol-precious-scheme', FALSE),
  ('Yes.  I never told him, but its worth was greater than     the value of The Shire!  ', 'GANDALF', 'The Fellowship of the Ring ', 'gandalf-great-worth', FALSE),
  ('We can''t do this by ourselves Sam. Not without a guide. I need you on my     side. ', 'FRODO', 'The Return of the King ', 'need-sam', FALSE),
  ('It''s a pity Bilbo didnt kill him when he had the chance ', 'FRODO', 'The Fellowship of the Ring ', 'frodo-regret', FALSE),
  ('We''re friends of Gandalf the Grey. Can you tell him we''ve     arrived? ', 'FRODO', 'The Fellowship of the Ring ', 'gandalf-arrival', FALSE),
  ('Night changes many thoughts. Sleep Eowyn. Sleep while you can. ', 'ARAGORN', 'The Return of the King ', 'night-changes-thought', FALSE),
  ('Here lies Balin, son of Fundin, Lord of Moria.    ,  He is dead then.    ,  Its as I feared. ', 'GANDALF', 'The Fellowship of the Ring ', 'balin-fallen-lord', FALSE),
  ('Agh!  Let them come There''s one dwarf yet in Moria who     still draws breath. ', 'GIMLI', 'The Fellowship of the Ring ', 'gimli-stands-tall', FALSE),
  (' How do we know this Strider is a friend of Gandalf ?  ', 'MERRY', 'The Fellowship of the Ring ', 'merry-knows-strider', FALSE),
  ('What did you tell him about Frodo and the Ring?      ', 'GANDALF', 'The Return of the King ', 'gandalf-reveals-truth', FALSE),
  ('There was no lie in Pippin''s eyes. A fool but an honest fool he remains.     ', 'GANDALF', 'The Return of the King ', 'honest-fool-pippin', FALSE),
  ('D''you hear that!  Rivendell! We''re going to see the     elves! ', 'SAM', 'The Fellowship of the Ring ', 'sam-sees-elves', FALSE),
  ('Don''t think he knows about second breakfast Pippin     ', 'MERRY', 'The Fellowship of the Ring ', 'second-breakfast-pippin', FALSE),
  ('I know you''ve run out. You smoke too much Pippin. ', 'MERRY', 'The Return of the King ', 'pippin-smoke-too-much', FALSE),
  ('Oh Smeagol Ive got one! , Ive got a fish Smeagol, Smeagol!    ', 'DEAGOL', 'The Return of the King ', 'deagol-caught-fish', FALSE),
  ('''Murderer'' they called us. They cursed us and drove us away.    ', 'SMEAGOL', 'The Return of the King ', 'smeagol-cursed-away', FALSE),
  ('Gollum'' Gollum'' Gollum'' , and we wept precious. We wept to be so alone.  ', 'SMEAGOL', 'The Return of the King ', 'smeagol-precious-tears', FALSE),
  ('and cool, so nice for feet'' and we only wish to catch a fish    , so juicy sweet.  ', 'SMEAGOL', 'The Return of the King ', 'smeagol-precious-fish', FALSE),
  ('No, it isn''t. It isn''t midday yet. , The days are growing darker.  ', 'FRODO', 'The Return of the King ', 'frodo-darkness-grows', FALSE),
  ('    Now come the days of the King. May they be blessed. ', 'GANDALF', 'The Return of the King ', 'gandalf-blesses-king', FALSE),
  ('    Et E''rello Endorenna ut''lien. Sinome maruvan ar Hildinyar tenn'' Ambar-metta!     ', 'ARAGORN', 'The Return of the King ', 'aragorn-endorenna-call', FALSE),
  ('uhh huh , I feel like I''m back at the Green Dragon.  ', 'PIPPIN', 'The Return of the King ', 'pippin-green-dragon', FALSE),
  ('A mug of ale in my hand. Putting my feet up on a settle after a hard     day''s work.  ', 'PIPPIN', 'The Return of the King ', 'pippin-ale-rest', FALSE),
  (' We are sitting on a field of     victory enjoying a few well earned comforts , The salted pork is particularly good.  ', 'PIPPIN', 'The Return of the King ', 'pippin-victory-feast', FALSE),
  ('Be careful. Even in defeat, Saruman is dangerous.  ', 'GANDALF', 'The Return of the King ', 'saruman-dangerous', FALSE),
  ('    I''m sorry uncle. I''m afraid I lost it.  ', 'FRODO', 'The Return of the King ', 'frodo-lost-ring', FALSE),
  ('    Oh, pity. (He sighs.) I would have like to have held it one last time.  ', 'BILBO', 'The Return of the King ', 'bilbo-final-hold', FALSE),
  ('    I think I''m quite ready for another adventure.  ', 'BILBO', 'The Return of the King ', 'bilbo-adventuring', FALSE),
  ('    , You don''t mean that. You can''t     leave. ', 'SAM', 'The Return of the King ', 'sam-dont-leave', FALSE),
  ('I''ve heard enough! Shoot him! Stick an arrow in his gob!  ', 'GIMLI', 'The Return of the King ', 'gimli-shoot-arrow', FALSE),
  ('No! Come down Saruman and your life will be spared!  ', 'GANDALF', 'The Return of the King ', 'saruman-mercy', FALSE),
  ('     I didn''t think it would end this way.   ', 'PIPPIN', 'The Return of the King ', 'pippin-unexpected-end', FALSE),
  ('  White shores and beyond,  a far green country under a swift sunrise.      ', 'GANDALF', 'The Return of the King ', 'gandalf-white-shores', FALSE),
  ('     The City has fallen silent.  There is no warmth left in the sun.       ', 'EOWYN', 'The Return of the King ', 'eowyn-silent-city', FALSE),
  ('Saruman! You were deep in the enemy''s counsel. Tell us what you know!  ', 'GANDALF', 'The Return of the King ', 'saruman-counsel', FALSE),
  ('  There''s plenty for the both of us, may be best Dwarf win!      ', 'GIMLI', 'The Return of the King ', 'gimli-wins-plenty', FALSE),
  ('  You see Mr Frodo some luck at last!     ', 'SAM', 'The Return of the King ', 'frodo-finds-luck', FALSE),
  ('    ,     Go back to the abyss! Fall into the nothingness that awaits you and your     master!  ', 'GANDALF', 'The Return of the King ', 'gandalf-abyss', FALSE),
  ('  Let the Lord of the Black Land come forth! ,  Let justice be done upon him!      ', 'ARAGORN', 'The Return of the King ', 'aragorn-justice-calls', FALSE),
  ('    Eomer, take your Eored down the left flank ', 'THEODEN', 'The Return of the King ', 'eomer-left-flank', FALSE),
  ('    Ride now, ride now! Ride! Ride for ruin and the world''s ending! DEATH! ', 'THEODEN', 'The Return of the King ', 'theoden-rides-ruin', FALSE),
  ('Oh! , That''s     it, right, we warned you! Prepare to be boarded!  ', 'GIMLI', 'The Return of the King ', 'gimli-prepares-battle', FALSE),
  ('Now that I''m here I don''t think I want to.  ', 'FRODO', 'The Return of the King ', 'frodo-hesitation', FALSE),
  ('  Sound the charge.  Take them head-on. Chaaarge! ,     ', 'THEODEN', 'The Return of the King ', 'theoden-charges', FALSE),
  ('Naughty little fly. Why does he cry? ,Caught in a web. Soon     you''ll be eaten.  ', 'GOLLUM', 'The Return of the King ', 'gollum-web-trap', FALSE),
  ('I have to destroy it Smeagol. , I have to destroy it for both our sakes.  ', 'FRODO', 'The Return of the King ', 'destroy-for-both', FALSE),
  ('I''m so sorry Sam.     I''m so sorry.  ', 'FRODO', 'The Return of the King ', 'frodo-apologizes-sam', FALSE),
  ('What kind of army would linger in such a place?  ', 'GIMLI', 'The Return of the King ', 'gimli-lingers-slow', FALSE),
  ('Little Hobbits do not belong in war Master Meriadoc.  ', 'THEODEN', 'The Return of the King ', 'hobbits-belong-not', FALSE),
  ('All my friends have gone to battle. I would be ashamed to be left     behind.  ', 'MERRY', 'The Return of the King ', 'merry-stands-tall', FALSE),
  (' The dead?     Summoned? I knew that! Huh. Huh. , Very good. Very good. , Legolas!  ', 'GIMLI', 'The Return of the King ', 'gimli-knows-dead', FALSE),
  ('It has been remade. ,     Fight for us and regain your honour. What say you? ,What say you? ', 'ARAGORN', 'The Return of the King ', 'aragorn-regain-honour', FALSE),
  ('I am Isildur''s heir. Fight for me and I will hold your oaths fulfilled.    ,What say you?     ', 'ARAGORN', 'The Return of the King ', 'aragorn-heir-oath', FALSE),
  ('You have my word! Fight and I will release you from this living death!    , What say you?  ', 'ARAGORN', 'The Return of the King ', 'aragorn-word-given', FALSE),
  ('Six thousand will not be enough to break the lines of Mordor.   ', 'ARAGORN', 'The Return of the King ', 'breaking-mordor-lines', FALSE),
  ('The horses are restless and the men are quiet. ', 'LEGOLAS', 'The Return of the King ', 'legolas-restless-steeds', FALSE),
  (' It is the road to the Dimholt, the door under the mountain.   ', 'LEGOLAS', 'The Return of the King ', 'legolas-dimholt-road', FALSE),
  ('Prepare for battle. Hurry men! To the wall! Defend the wall! Over here!     Return to your posts. ', 'GANDALF', 'The Return of the King ', 'gandalf-calls-battle', FALSE),
  ('I''m ready!  , Sorry.  It isn''t all that dangerous.  It''s not     even sharp.   ', 'MERRY', 'The Return of the King ', 'merry-ready-courage', FALSE),
  ('Hold them back, do not give in to fear. Stand to your posts. Fight!  ', 'GANDALF', 'The Return of the King ', 'gandalf-stand-firm', FALSE),
  ('Not at the towers! Aim for the trolls, kill the trolls! ', 'GANDALF', 'The Return of the King ', 'gandalf-troll-hunt', FALSE),
  ('Fight them back! ,Peregrin Took! Go back to the Citadel. ', 'GANDALF', 'The Return of the King ', 'gandalf-citadel-stand', FALSE),
  ('Guard of the Citadel indeed! , Now back up the hill     quickly. Quick!  ', 'GANDALF', 'The Return of the King ', 'gandalf-citadel-guard', FALSE),
  ('Murderers, traitors. You would call upon them to fight?  They believe in     nothing.  They answer to no one ', 'ARAGORN', 'The Return of the King ', 'aragorn-accusations', FALSE),
  ('Sauron will not have forgotten the sword of Elendil.   ', 'ARAGORN', 'The Return of the King ', 'aragorn-sword-elendil', FALSE),
  ('The blade that was broken shall return to Minas Tirith.   ', 'ARAGORN', 'The Return of the King ', 'aragorn-blade-returns', FALSE),
  ('What were you thinking Peregrin Took?  What service can a Hobbit offer     such a great lord of men?    ', 'PIPPIN', 'The Return of the King ', 'pippin-humble-service', FALSE),
  ('I didn''t think they would find any livery that would  fit me.  ', 'PIPPIN', 'The Return of the King ', 'pippin-livery-fit', FALSE),
  ('It is but a shadow and a thought that you love.  I cannot give you what     you seek.  ', 'ARAGORN', 'The Return of the King ', 'shadow-love-aragorn', FALSE),
  ('Not this time.  This time you must stay Gimli.  ', 'ARAGORN', 'The Return of the King ', 'gimli-stay-behind', FALSE),
  ('Well, I''m taller than you were then.  Though, I''m not likely to grow     anymore, except sideways.   ', 'PIPPIN', 'The Return of the King ', 'pippin-grows-sideways', FALSE),
  ('I think you have strength of a different kind.  And one day your father     will see it.   ', 'PIPPIN', 'The Return of the King ', 'pippin-different-strength', FALSE),
  ('It''s always dark here.  ,  It''s gone!     , The elven bread!     ', 'SAM', 'The Return of the King ', 'sam-dark-bread', FALSE),
  ('  He doesn''t     eat it. , He can''t have taken     it.   ', 'FRODO', 'The Return of the King ', 'frodo-cannot-eat', FALSE),
  ('That''s a filthy lie!  ,      You stinking, two faced sneak!   ', 'SAM', 'The Return of the King ', 'sam-calls-out', FALSE),
  ('Faramir?  This is not the first Halfling to have crossed your path. ', 'GANDALF', 'The Return of the King ', 'faramir-crossroads', FALSE),
  ('I don''t want to keep it.  , I just want to help.   ', 'SAM', 'The Return of the King ', 'sam-helps-willingly', FALSE),
  ('  Faramir!  Faramir!     , Your     father''s will has turned to madness.  Do not throw away your life so     rashly.   ', 'GANDALF', 'The Return of the King ', 'faramir-madness', FALSE),
  ('Your father loves you Faramir.  ,  He will remember it before the end.   ', 'GANDALF', 'The Return of the King ', 'father-loves-faramir', FALSE),
  ('Sauron''s wrath will be terrible, his retribution swift.           ', 'GANDALF', 'The Two Towers ', 'sauron-wrath', FALSE),
  ('The battle for Helm''s Deep is over. The battle for Middle-earth is about to begin.           ', 'GANDALF', 'The Two Towers ', 'gandalf-begins-war', FALSE),
  ('Master. Master looks after us. ,Master wouldn''t hurt us.           ', 'SMEAGOL', 'The Two Towers ', 'smeagol-trusts-master', FALSE),
  ('Careful master!  Careful.   Very far to fall.  Very dangerous are the     stairs.   ', 'GOLLUM', 'The Return of the King ', 'gollum-careful-stairs', FALSE),
  ('But the fat Hobbit, he knows.      Eyes always watching.           ', 'SMEAGOL', 'The Two Towers ', 'smeagol-watching-eyes', FALSE),
  ('Come on, Hobbits. Long ways to go yet. , Smeagol will show you the way.           ', 'SMEAGOL', 'The Two Towers ', 'smeagol-smeagol-shows-way', FALSE),
  ('Forty-two? That''s not bad for a pointy-eared Elvish princeling. I myself am sitting pretty on 43.,     ', 'GIMLI', 'The Two Towers ', 'gimli-pointy-ears', FALSE),
  ('He was twitching......because he''s got my axe ,embedded in his nervous system!           ', 'GIMLI', 'The Two Towers ', 'gimli-axe-embedded', FALSE),
  ('He doesn''t look too happy, does he?           ', 'MERRY', 'The Two Towers ', 'merry-unhappy-glance', FALSE),
  ('Oh, yes. It''s a quality establishment. I hear the staff are very good.           ', 'PIPPIN', 'The Two Towers ', 'pippin-quality-staff', FALSE),
  ('Good luck trying to find something decent around here. ,Probably only dead rats and      mouldy bread.,     ', 'MERRY', 'The Two Towers ', 'merry-moldy-bread', FALSE),
  ('Longbottom Leaf. ,The finest pipe-weed in South Farthing.           ', 'MERRY', 'The Two Towers ', 'merry-pipeweed', FALSE),
  ('It''s perfect. One barrel each.,Wait.      Do you think we should share it with Treebeard?           ', 'PIPPIN', 'The Two Towers ', 'pippin-perfect-barrel', FALSE),
  ('Share it? ,No. No. ,Dead plant and all that. Don''t think he''d understand. ,Could be a distant relative.           ', 'MERRY', 'The Two Towers ', 'merry-distant-relative', FALSE),
  ('Captain Faramir......you have shown your quality, sir.           ', 'SAM', 'The Two Towers ', 'faramir-quality', FALSE),
  ('So there''s no hard feelings. Forgive and forget.           ', 'SAM', 'The Two Towers ', 'sam-forgives-all', FALSE),
  ('No, no, no hard feelings. Gollum, Gollum. ,Yes, master. Nice Hobbits.           ', 'GOLLUM', 'The Two Towers ', 'gollum-nice-hobbits', FALSE),
  ('It''s calling to him, Sam. His Eye is almost on me.            ', 'FRODO', 'The Two Towers ', 'eye-calling-frodo', FALSE),
  ('Is there no other way for the women      and children to get out of the caves?     ', 'ARAGORN', 'The Two Towers ', 'aragorn-safe-passage', FALSE),
  (' Tell the women and children      to make for the mountain pass. And barricade the entrance!           ', 'ARAGORN', 'The Two Towers ', 'aragorn-mountain-pass', FALSE),
  ('Aragorn! Fall back to the Keep! Get your men out of there!,     ', 'THEODEN', 'The Two Towers ', 'theoden-retreat', FALSE),
  ('So much death. ,  What can Men do against such reckless hate?           ', 'THEODEN', 'The Two Towers ', 'theoden-despair', FALSE),
  ('Yes.........Yes.........The horn of Helm Hammerhand......shall sound in the Deep......one last time.           ', 'THEODEN', 'The Two Towers ', 'helm-last-call', FALSE),
  ('Let this be the hour      when we draw swords together. ,     ', 'THEODEN', 'The Two Towers ', 'theoden-draws-swords', FALSE),
  ('Fell deeds, awake. Now for wrath......now for ruin and a red dawn.,     ', 'THEODEN', 'The Two Towers ', 'theoden-wrath', FALSE),
  ('They have broken through! The castle is breached. Retreat!       ', 'THEODEN', 'The Two Towers ', 'theoden-castle-breached', FALSE),
  ('Well, lad, whatever luck you live by, let''s hope it lasts the night.       ', 'GIMLI', 'The Two Towers ', 'gimli-lasting-luck', FALSE),
  (' A      Eruch''n, ''-dano i faelas a hyn an uben tanatha le faelas! ,     ', 'ARAGORN', 'The Two Towers ', 'aragorn-elvish-tongue', FALSE),
  ('Shall I describe it to you? Or would you like me to find you a box?        ', 'LEGOLAS', 'The Two Towers ', 'legolas-box-find', FALSE),
  (' Faeg i-varv d''n na lanc a      nu ranc. ', 'LEGOLAS', 'The Two Towers ', 'legolas-ancient-tongue', FALSE),
  ('Hasty? Our friends are out there. ,They need our help. They cannot fight this war on their own.       ', 'MERRY', 'The Two Towers ', 'merry-stands-true', FALSE),
  ('Leaves more time for drinking!     Break out the ale! These men are thirsty!     ', 'BOROMIR', 'The Two Towers ', 'boromir-ale-time', FALSE),
  ('Remember today, little brother. Today, life is good. ', 'BOROMIR', 'The Two Towers ', 'boromir-remember-today', FALSE),
  ('They exaggerate. The victory belongs to Faramir also.  ', 'BOROMIR', 'The Two Towers ', 'boromir-shares-glory', FALSE),
  ('No. My place is here with     my people. ,Not in Rivendell. ', 'BOROMIR', 'The Two Towers ', 'boromir-people-place', FALSE),
  ('Arwen. ,Tollen i l''. I chair gwannar     na Valannor. Si bado, no c''rar. ', 'ELROND', 'The Two Towers ', 'arwen-valannor', FALSE),
  ('Of course he did. I told you he was tricksy. I told you he was false. ', 'GOLLUM', 'The Two Towers ', 'gollum-tricksy-false', FALSE),
  ('Filthy little     Hobbitses! They stole it from us! ', 'GOLLUM', 'The Two Towers ', 'gollum-theft-betrayal', FALSE),
  ('I amar prestar aen... han mathon ne nen, han mathon ne chae a han noston     ned ''wilith.                     ', 'GALADRIEL', 'The Two Towers ', 'galadriel-amar-prestar', FALSE),
  ('I want every man and strong     lad able to bear arms......to be ready for battle by nightfall.    ', 'THEODEN', 'The Two Towers ', 'theoden-rallies-warriors', FALSE),
  ('This is no rabble of mindless Orcs. These are Uruk-hai. Their armour is     thick and their shields broad. ', 'GIMLI', 'The Two Towers ', 'gimli-uruk-threat', FALSE),
  ('I have fought many wars, Master Dwarf. I know how to defend my own keep. ', 'THEODEN', 'The Two Towers ', 'theoden-defends-keep', FALSE),
  ('Send out riders, my lord. You must call for aid.  ', 'ARAGORN', 'The Two Towers ', 'riders-call-aid', FALSE),
  ('Yes, precious. False.They will cheat you, hurt you, lie!  ', 'GOLLUM', 'The Two Towers ', 'gollum-precious-lies', FALSE),
  ('You don''t have any friends.Nobody likes you. ', 'GOLLUM', 'The Two Towers ', 'gollum-friendless', FALSE),
  ('There is no time. War is upon us. Secure the gate. ', 'THEODEN', 'The Two Towers ', 'theoden-calls-war', FALSE),
  ('I will not leave my daughter hereto die. ', 'ELROND', 'The Two Towers ', 'elrond-stands-firm', FALSE),
  ('Master looks after us now.We don''t need you. ', 'SMEAGOL', 'The Two Towers ', 'smeagol-masters-care', FALSE),
  ('Edra le men, men na guil edwen. Haer o auth a n''r a naeth. ', 'ARAGORN', 'The Two Towers ', 'aragorn-destiny-calls', FALSE),
  ('I am mortal. You are Elf-kind.It was a dream, Arwen.Nothing more. ', 'ARAGORN', 'The Two Towers ', 'aragorn-mortal-dream', FALSE),
  ('She is sailing to the Undying Landswith all that is left of her kin. ', 'ARAGORN', 'The Two Towers ', 'arwen-sailing-west', FALSE),
  ('We told him to go away.And away he goes, precious. ,Gone! Gone! Gone!Smeagol is free! ', 'SMEAGOL', 'The Two Towers ', 'smeagol-goes-free', FALSE),
  ('They are young.They are tender. They are nice.Yes, they are. Eat them. Eat them!    ', 'GOLLUM', 'The Two Towers ', 'gollum-precious-meal', FALSE),
  ('What''s it doing?Stupid, fat Hobbit.It ruins it. ', 'GOLLUM', 'The Two Towers ', 'gollum-fat-hobbit', FALSE),
  ('Boil them, mash themstick them in a stew.Lovely, big, golden chipswith a nice piece of fried fish.  ', 'SAM', 'The Two Towers ', 'sam-golden-chips', FALSE),
  ('Oh, yes, we could.Spoil a nice fish. ,Give it to us raw...    ,...and wriggling.You keep nasty chips. ', 'GOLLUM', 'The Two Towers ', 'gollum-raw-fish', FALSE),
  ('Women of this country learned long ago:Those without swordscan still die upon them.I fear neither death nor pain. ', 'EOWYN', 'The Two Towers ', 'eowyn-fearless', FALSE),
  ('You must lead the peopleto Helm''s Deep, and make haste. ', 'THEODEN', 'The Two Towers ', 'theoden-helm-deep', FALSE),
  ('To make his war.The last war that will coverall the world in Shadow. ', 'GOLLUM', 'The Two Towers ', 'gollum-shadow-war', FALSE),
  ('We''ve lingered here too long.Come on, Sam. ', 'FRODO', 'The Two Towers ', 'frodo-come-on', FALSE),
  ('Can''t you hear yourself?Don''t you know who you sound like?  ', 'SAM', 'The Two Towers ', 'sam-hear-yourself', FALSE),
  ('Tell me what happenedand I will ease your passing. ', 'GIMLI', 'The Two Towers ', 'gimli-ease-passing', FALSE),
  ('Get the wounded on horses.The wolves of lsengard will return.Leave the dead. ', 'THEODEN', 'The Two Towers ', 'theoden-wounded-horses', FALSE),
  ('     Never thought I''d die fighting side by side with an elf.  ', 'GIMLI', 'The Return of the King ', 'gimli-elf-alliance', FALSE),
  ('It''s all right. Nobody panic.That was deliberate.It was deliberate. ', 'GIMLI', 'The Two Towers ', 'gimli-deliberate', FALSE),
  ('Our people are safe.We have paid for it with many lives. ', 'THEODEN', 'The Two Towers ', 'theoden-safety-cost', FALSE),
  ('Draw all our forces behind the wall.Bar the gate.And set a watch on the surround. ', 'THEODEN', 'The Two Towers ', 'theoden-fortress-command', FALSE),
  ('They flee to the mountains when they should stand and fight. Who will     defend them if not their king? ', 'GIMLI', 'The Two Towers ', 'gimli-stands-firm', FALSE),
  ('    Clever Hobbits to climb so high! ,Mustn''t go that way. Mustn''t hurt the     precious! ', 'GOLLUM', 'The Return of the King ', 'gollum-precious-obsession', FALSE),
  ('Oh, save us.My old Gaffer would have a thing or twoto say if he could see us now. ', 'SAM', 'The Two Towers ', 'sam-gaffer-wisdom', FALSE),
  ('Look!The gate.It''s opening!I can see a way down. ', 'SAM', 'The Two Towers ', 'sam-gate-opens', FALSE),
  ('I made some stew.It isn''t much, but it''s hot.  ', 'EOWYN', 'The Two Towers ', 'eowyn-hot-stew', FALSE),
  ('There are few of us left.The Northern Kingdomwas destroyed long ago. ', 'ARAGORN', 'The Two Towers ', 'aragorn-few-left', FALSE),
  (' F''ste, stille n'',     f''ste, stille n''. Lac is drefed, gefr''gon. ', 'ARAGORN', 'The Two Towers ', 'aragorn-stillness-call', FALSE),
  ('I do not ask you to come with me, Sam. ', 'FRODO', 'The Two Towers ', 'frodo-asks-sam', FALSE),
  ('No! , There''s another way.More secret. A dark way. ', 'GOLLUM', 'The Two Towers ', 'gollum-secret-way', FALSE),
  ('Yes. There''s a path......and some stairs.And then......a tunnel. ', 'GOLLUM', 'The Two Towers ', 'gollum-winding-path', FALSE),
  ('  Merry! ,  Merry it''s me.    ,  It''s Pippin!      ', 'PIPPIN', 'The Return of the King ', 'pippin-calls-merry', FALSE),
  ('  No Merry, I''m going to look after you.      ', 'PIPPIN', 'The Return of the King ', 'pippin-looks-after', FALSE),
  ('Three days and nights pursuit.No food. No rest.And no sign of our quarrybut what bare rock can tell. ', 'GIMLI', 'The Two Towers ', 'gimli-pursuit', FALSE),
  ('It''s talking, Merry.The tree is talking. ', 'PIPPIN', 'The Two Towers ', 'pippin-talking-tree', FALSE),
  ('A tree-herder.A shepherd of the forest. ', 'MERRY', 'The Two Towers ', 'merry-tree-herder', FALSE),
  ('It''s Saruman''s army.The war has started.', 'MERRY', 'The Two Towers ', 'saruman-strikes', FALSE),
  ('    No! , Don''t you let go! Don''t let go! Reeeaaach!     ', 'SAM', 'The Return of the King ', 'sam-reach-far', FALSE),
  ('     I''m glad to be with you Samwise Gamgee here at the end of all things.     They hug. ', 'FRODO', 'The Return of the King ', 'frodo-samwise-end', FALSE),
  ('     I go to my fathers, in whose mighty company; I shall not now feel ashamed.      ', 'THEODEN', 'The Return of the King ', 'theoden-mighty-company', FALSE),
  ('  Bad idea!  Very handy in a tight spot these lads, despite the fact they''re dead.     ', 'GIMLI', 'The Return of the King ', 'gimli-handy-dead', FALSE),
  ('  I hold your oath fulfilled.  Go.  Be at peace.     ', 'ARAGORN', 'The Return of the King ', 'oath-fulfilled', FALSE),
  ('Please, Merry.You''re what? Three-foot-six? At the most?Whereas me, I''m pushing 3''7". ,3''8"! ', 'PIPPIN', 'The Two Towers ', 'pippin-height-jest', FALSE),
  ('See? See?We''ve led you out.Hurry, Hobbitses. Hurry! Very lucky we find you.    ,Nice Hobbit. ', 'GOLLUM', 'The Two Towers ', 'gollum-guides-hobbits', FALSE),
  ('It''s a bog. He''s led us into a swamp. ', 'SAM', 'The Two Towers ', 'sam-swamp-led', FALSE),
  ('I hate this place. It''s too quiet.There''s been no sight nor soundof a bird for two days. ', 'SAM', 'The Two Towers ', 'sam-silent-despair', FALSE),
  ('No, no birdses to eat.No crunchable birdses.We are famished! Yes!Famished we are, precious!  ', 'GOLLUM', 'The Two Towers ', 'gollum-famished-precious', FALSE),
  ('Bogs and ropeand goodness knows what.It''s not natural. None of it. ', 'SAM', 'The Two Towers ', 'sam-unnatural-bogs', FALSE),
  ('Nothing.Just a bit of seasoning.I thought maybe if we was havinga roast chicken one night or something. ', 'SAM', 'The Two Towers ', 'sam-roast-chicken', FALSE),
  ('Ssh!As soon as they find out we don''twe''re dead. ', 'MERRY', 'The Two Towers ', 'merry-found-dead', FALSE),
  ('  I thought I''d lost you.  So I took it, only for safekeeping.      ', 'SAM', 'The Return of the King ', 'sam-safekeeping', FALSE),
  ('  If Sauron had the Ring we would know it.      ', 'ARAGORN', 'The Return of the King ', 'aragorn-would-know', FALSE),
  ('  Let him stay there!  Let him rot!  Why should we care?     ', 'GIMLI', 'The Return of the King ', 'gimli-rot-there', FALSE),
  ('There are dead things!Dead faces in the water. ', 'SAM', 'The Two Towers ', 'sam-dead-faces', FALSE),
  ('Careful now! Or Hobbits go downto join the dead ones......and light little candlesof their own. ', 'GOLLUM', 'The Two Towers ', 'gollum-careful-warning', FALSE),
  ('Master should be resting.Master needs to keep up his strength. ', 'GOLLUM', 'The Two Towers ', 'gollum-strength-rest', FALSE),
  ('Mustn''t ask us. Not its business.Gollum. Gollum. ', 'GOLLUM', 'The Two Towers ', 'gollum-business-not', FALSE);
