// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Pings Postgres and Redis in parallel (2s timeout) and reports each dependency's live status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "one or more dependencies unreachable",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/links": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a summary of every non-deleted link owned by the authenticated API key, including expired links (expiry stops redirects, not the owner's dashboard).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "links"
                ],
                "summary": "List the caller's own links",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ListLinksResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Selects an available LOTR-themed slug from the quote pool and maps it to the provided URL. The link expires after the configured TTL (default 30 days).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "links"
                ],
                "summary": "Create a shortened link",
                "parameters": [
                    {
                        "description": "URL to shorten",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateLinkRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateLinkResponse"
                        }
                    },
                    "400": {
                        "description": "missing body, or url is empty, malformed, non-http(s), or too long",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal error (slug pool exhausted, DB failure)",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/links/{slug}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Soft-deletes the link (sets is_active = false) and evicts it from the Redis cache. The slug is not returned to the pool. Only the link's owner may delete it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "links"
                ],
                "summary": "Delete a shortened link",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"one-ring-to-rule\"",
                        "description": "URL slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "slug not found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/links/{slug}/stats": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns metadata (click count, expiry, active status), the 10 most recent click events, and per-day click counts for the last 7 days for the given slug.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "links"
                ],
                "summary": "Get link statistics",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"one-ring-to-rule\"",
                        "description": "URL slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.StatsResponse"
                        }
                    },
                    "404": {
                        "description": "slug not found, deleted, or not owned by caller",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/session": {
            "post": {
                "description": "Generates a new random API key with no login/signup required. The key's expiry slides forward on every authenticated request, so an active visitor never loses access; only abandoned keys age out.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Mint an anonymous session key",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.SessionResponse"
                        }
                    },
                    "500": {
                        "description": "internal error (key generation or DB failure)",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{slug}": {
            "get": {
                "description": "Resolves a slug to its original URL (Redis cache first, then DB) and issues a 302 redirect. Click metadata is recorded asynchronously. Returns 410 if the link has expired.",
                "tags": [
                    "redirect"
                ],
                "summary": "Redirect to original URL",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"one-ring-to-rule\"",
                        "description": "URL slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Location header set to the original URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "slug not found or inactive",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "410": {
                        "description": "link has expired",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ClickResponse": {
            "type": "object",
            "properties": {
                "clicked_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip_address": {
                    "type": "string",
                    "example": "127.0.0.1"
                },
                "referrer": {
                    "type": "string",
                    "example": "https://google.com"
                },
                "slug": {
                    "type": "string",
                    "example": "one-ring-to-rule"
                },
                "user_agent": {
                    "type": "string",
                    "example": "Mozilla/5.0"
                }
            }
        },
        "handlers.CreateLinkRequest": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "https://example.com/some/very/long/path"
                }
            }
        },
        "handlers.CreateLinkResponse": {
            "type": "object",
            "properties": {
                "original": {
                    "type": "string",
                    "example": "https://example.com/some/very/long/path"
                },
                "short_url": {
                    "type": "string",
                    "example": "http://localhost:8080/one-ring-to-rule"
                },
                "slug": {
                    "type": "string",
                    "example": "one-ring-to-rule"
                }
            }
        },
        "handlers.DailyClickResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 42
                },
                "date": {
                    "type": "string",
                    "example": "2026-07-23"
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "slug not found"
                }
            }
        },
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "cache": {
                    "type": "string",
                    "example": "connected"
                },
                "database": {
                    "type": "string",
                    "example": "connected"
                },
                "service": {
                    "type": "string",
                    "example": "lembas-links"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handlers.LinkSummary": {
            "type": "object",
            "properties": {
                "click_count": {
                    "type": "integer",
                    "example": 42
                },
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "original": {
                    "type": "string",
                    "example": "https://example.com"
                },
                "short_url": {
                    "type": "string",
                    "example": "http://localhost:8080/one-ring-to-rule"
                },
                "slug": {
                    "type": "string",
                    "example": "one-ring-to-rule"
                }
            }
        },
        "handlers.ListLinksResponse": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.LinkSummary"
                    }
                }
            }
        },
        "handlers.SessionResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string",
                    "example": "a1b2c3d4..."
                },
                "expires_at": {
                    "type": "string"
                }
            }
        },
        "handlers.StatsResponse": {
            "type": "object",
            "properties": {
                "click_count": {
                    "type": "integer",
                    "example": 42
                },
                "created_at": {
                    "type": "string"
                },
                "daily_clicks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.DailyClickResponse"
                    }
                },
                "expires_at": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "original": {
                    "type": "string",
                    "example": "https://example.com"
                },
                "recent_clicks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ClickResponse"
                    }
                },
                "short_url": {
                    "type": "string",
                    "example": "http://localhost:8080/one-ring-to-rule"
                },
                "slug": {
                    "type": "string",
                    "example": "one-ring-to-rule"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key prefixed with \"Bearer \" (e.g. \"Bearer my-api-key\")",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "54.164.172.135",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Lembas Links API",
	Description:      "A Lord of the Rings-themed URL shortener. Authenticated routes require an API key passed as a Bearer token in the Authorization header.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
